sonar.projectKey=sinch-developer-experience_sinch-mcp-server
sonar.organization=sinch-developer-experience

sonar.sources=src
sonar.tests=tests
sonar.exclusions=**/node_modules/**,**/dist/**,coverage/**
sonar.typescript.tsconfigPath=tsconfig.json
