import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { registerCreateConversationApp } from './create-conversation-app';
import { registerSetRcsChannelOnApp } from './set-rcs-channel-on-app';
import { registerSetSmsChannelOnApp } from './set-sms-channel-on-app';
import { registerSetWhatsAppChannelOnApp } from './set-whatsapp-channel-on-app';
import { registerListAllApps } from './list-all-apps';
import { registerListAllTemplates } from './list-messaging-templates';
import { registerSendCardOrChoiceMessage } from './send-card-or-choice-message';
import { registerSendLocationMessage } from './send-location-message';
import { registerSendMediaMessage } from './send-media-message';
import { registerSendTemplateMessage } from './send-template-message';
import { registerSendWhatsAppTemplateMessage } from './send-whatsapp-template-message';
import { registerSendTextMessage } from './send-text-message';
import { registerListWebhooks } from './list-webhooks';
import { registerGetWebhook } from './get-webhook';
import { registerCreateWebhook } from './create-webhook';
import { registerUpdateWebhook } from './update-webhook';
import { registerDeleteWebhook } from './delete-webhook';
import { Tags } from '../../types';

export const registerConversationTools = (server: McpServer, tags: Tags[]) => {
  registerSendTextMessage(server, tags);
  registerSendMediaMessage(server, tags);
  registerSendLocationMessage(server, tags);
  registerSendCardOrChoiceMessage(server, tags);
  registerSendTemplateMessage(server, tags);
  registerSendWhatsAppTemplateMessage(server, tags);
  registerListAllApps(server, tags);
  registerCreateConversationApp(server, tags);
  registerSetSmsChannelOnApp(server, tags);
  registerSetRcsChannelOnApp(server, tags);
  registerSetWhatsAppChannelOnApp(server, tags);
  registerListAllTemplates(server, tags);
  registerListWebhooks(server, tags);
  registerGetWebhook(server, tags);
  registerCreateWebhook(server, tags);
  registerUpdateWebhook(server, tags);
  registerDeleteWebhook(server, tags);
};
